# This workflow will build and push a new container image to Docker Hub

name: Build a docker image

on: [push]

env:
  DOCKER_REPOSITORY: github_action

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and push image to docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        id: login-docker
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          DOCKER_REGISTRY: mayekarruchi
          IMAGE_TAG: v1
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
        
